### ISSUE TITLE
Please add support Ralink/Mediatek RT series WiFi USB

### ISSUE THREAD

**Issue by UniqueC0de** [chris1111/Wireless-USB-Adapter-Clover#1]
Ralink/Mediatek RT2870/ RT2770/ RT3X7X/ RT537X/ RT5572

**Comment by chris1111** [comment]
This Drivers its here https://github.com/chris1111/TP-LINK-WIFI-Network-macOS

**Comment by UniqueC0de** [comment]
so you mean I can use driver from [https://github.com/chris1111/TP-LINK-WIFI-Network-macOS](url), and use [https://github.com/chris1111/Wireless-USB-Adapter-Clover](url) configuration utility?

**Comment by chris1111** [comment]
No the utilities are diferant

**Comment by UniqueC0de** [comment]
Ok, I want is after configure the internet connection.
I want the internet to be connected without configuration utility to be visible when macOS startup, or when we tap on Turn WiFi On button.

This configuration utility is kind of annoying that appears each time when I start macOS.

Anyway, thanks for your reply.

**Comment by chris1111** [comment]
Yes this utility is different, utility to be visible when macOS startup but its not a big deal
