### ISSUE TITLE
Incompatible with Adobe XD

### ISSUE THREAD

**Issue by wdhwg001** [chris1111/Wireless-USB-Adapter-Clover#100]
Hi,

I'm using a Netgear A6150 with this driver, but the driver stops working once I started Adobe XD. In detail, the icon hangs with no responses and the network disconnected until I close Adobe XD and replug the USB WiFi.

I don't have much experience with debugging such incompatibilities, but I do notice that Adobe XD uses libusb. I suppose it uses that to communicate with the mobile app to provide on-device previews. I'm personally not quite interested in this feature, as being incompatible with a WiFi driver is much more frustrating.

I did post feedback to Adobe, but I suspect they won't care as this driver is pretty much for Hackintosh only. Therefore, is there any way to workaround or fix this here?

By the way, I'm now using macOS Catalina 10.15.4 (19E287) on a 15 inch Surface Book 2.

Thanks!

**Comment by chris1111** [comment]
Why not trying a macOS Update ?

**Comment by ymc3** [comment]
> Why not trying a macOS Update ?

you mean upgrade to big sur?

**Comment by chris1111** [comment]
No update 10.15.7
