### ISSUE TITLE
Getting error on installation 

### ISSUE THREAD

**Issue by ronak4567** [chris1111/Wireless-USB-Adapter-Clover#104]
Not install on Hacintos Catalina

[](url)
![Screenshot 2021-04-22 at 1 00 21 PM](https://user-images.githubusercontent.com/23085409/115674150-fcea3380-a36a-11eb-966f-044ddb542b5c.png)
![Screenshot 2021-04-22 at 1 00 56 PM](https://user-images.githubusercontent.com/23085409/115674164-007dba80-a36b-11eb-92f8-04f2f88e0ff5.png)

**Comment by chris1111** [comment]
this is for the menue bar Icon 🥸
