### ISSUE TITLE
Wifi Not Running

### ISSUE THREAD

**Issue by myworkfloww** [chris1111/Wireless-USB-Adapter-Clover#107]
Hello Guys, I have Been trying to Install macOS Sierra, Latest version on my Laptop but have faced multiple problems, I hope you guys can help.

 

System Specs:

System Manufacturer: Haier Computer
System Model: Y11B
Processor: Intel® Core M-5Y10c CPU @ 0.80GHz (4﻿﻿ CPUs), ~1.0GHz
Ram : 4GB
VGA : Intel® HD Graphics 5300
Resolution: 1366 x 768(p﻿)
Network Adapter : RealTekRTL8723B wireless LAN 802.11n USB 2.0 Network Adapter 
Sound Card : High Definition Audio Device﻿﻿﻿﻿

Actually I am facing wifi problem i have installed Wireless USB Adapter Clover-V16.pkg but not working wifi.
Network Adapter is dictated but not connecting to internet. please check in picture. also wifi icon is missing from top bar.
![Screen Shot 2015-08-22 at 8 55 50 PM](https://user-images.githubusercontent.com/62444406/131238794-ada0b91b-1818-414a-b6d0-8dc07b013be8.png)

Could anyone help?

**Comment by chris1111** [comment]
RTL8723B is not support in macOS , only in Linux and Windows
