### ISSUE TITLE
Generic chinese USB WIFI Dongle

### ISSUE THREAD

**Issue by jokowijembut** [chris1111/Wireless-USB-Adapter-Clover#108]
i have generic cheap usb wifi dongle, it works properly in windows but i cant make it work in hackintosh i think its because driver issue. 
i already tried Wireless USB Adapter Clover-V16.pkg and it still cant make it work. based on windows device manager the chipset is RTL8818FTV. im wondering if your driver can mane my cheap dongle working. thanks 🙌

**Comment by chris1111** [comment]
The RTL88 only 11, 12, 14 work 
RTL8818FTV not work in macOS
