### ISSUE TITLE
Support for Realtek 8192EU(ASUS PCE-N15) and Realtek 8812AE(ASUS PCE-AC51) PCI Realtek wifi adapters.

### ISSUE THREAD

**Issue by darkstar252** [chris1111/Wireless-USB-Adapter-Clover#109]
I don't know if there is easy or not , but to add the device id's for this card make this universal package great if someone have a PCI Wireless NIC with realtek chips , like me. :)

Thank you very much.

**Comment by chris1111** [comment]
Its not possible because no source exist
