### ISSUE TITLE
WiFi adapter will not reconnect after restart

### ISSUE THREAD

**Issue by ZhuJo** [chris1111/Wireless-USB-Adapter-Clover#11]
After restart/shutdown of hackintosh with macOs 10.14.3 (v5 of drivers) adapter will not automatically connect to hidden WiFi network (WPA2 AES) it was previously connected to.

**Comment by chris1111** [comment]
> After restart/shutdown of hackintosh with macOs 10.14.3 (v5 of drivers) adapter will not automatically connect to hidden WiFi network (WPA2 AES) it was previously connected to.

Thanks
what should you do to connect it ?
otherwise use the v4 if it works best for you

**Comment by ZhuJo** [comment]
behaviour was the same with v4.

I have to again enter network name and password. Connecting to Time Capsule.

Jozef

**Comment by chris1111** [comment]
which adapter you use

**Comment by ZhuJo** [comment]
it's noname adapter based on Realtek 8812AU.
From System Profiler:
USB3.0 802.11ac 1200M Adapter:

  Product ID:	0xb812
  Vendor ID:	0x0bda  (Realtek Semiconductor Corp.)
  Version:	2.10
  Serial Number:	123456
  Speed:	Up to 480Mb/sec
  Manufacturer:	Realtek
  Location ID:	0x14400000 / 11
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

**Comment by ZhuJo** [comment]
You can close the issue, I have solved it by installing Mac drivers instead. 
Clover drivers are behaving bad since beginning – first of all, your installer can't mount EFI partition and thus install drivers to /EFI/CLOVER/kexts/others so it has to be done manually. 

Also, folder WLAN in /Library/Application Support has wrong permissions and is readable only by root.
