### ISSUE TITLE
New version: Driver 1830.32.b2 and UI 5.0.8.b5

### ISSUE THREAD

**Issue by pexcn** [chris1111/Wireless-USB-Adapter-Clover#15]
Here: 
Direct

**Comment by chris1111** [comment]
> Here:
> Direct
Not accept because this version not working for all support adapter

**Comment by pexcn** [comment]
Where did you get the latest version?

**Comment by chris1111** [comment]
> Where did you get the latest version?

its from TP Link

**Comment by pexcn** [comment]
> > Here:
> > Direct
> > Not accept because this version not working for all support adapter
> > Thank you anyway

Hi, this version I tried it can use my TK-Link (WN725N V2), It seems because it is the same chipset (RTL8188EU).
