### ISSUE TITLE
Can you add support for TP-Link WN725N V1? (RT8188CUS)

### ISSUE THREAD

**Issue by atsushidev** [chris1111/Wireless-USB-Adapter-Clover#17]
Hi,
I have a "TP-Link WN725N V1 Wireless USB Adapter". Can you please add support it?
The chipset is RT8188CUS. I'm on Mojave 10.14.5.

Thank you!

**Comment by chris1111** [comment]
> Hi,
> I have a "TP-Link WN725N V1 Wireless USB Adapter". Can you please add support it?
> The chipset is RT8188CUS. I'm on Mojave 10.14.5.
> 
> Thank you!

Thats impossible its not the same chipset
