### ISSUE TITLE
Can you please add support for Ralink chipset RA2870?

### ISSUE THREAD

**Issue by zhouhesheng** [chris1111/Wireless-USB-Adapter-Clover#18]
Hi, this is a great project. 

I'm using a USB wifi with ralink rt2870 chipset. the file RT2870USBWirelessDriver.kext is 64 bit. But the wireless utility and the RaWLAPI.framework file are not 64 bit, so they can not work in 10.15.
Can you please add support for rt2870? or do you have any idea how to make it work?

Thanks.

**Comment by chris1111** [comment]
[Same here](https://github.com/chris1111/Wireless-USB-Adapter-Clover/issues/17)
