### ISSUE TITLE
AC56 Issues

### ISSUE THREAD

**Issue by daniel-farina** [chris1111/Wireless-USB-Adapter-Clover#19]
Hello Guys, 

I'm trying to make this network adapter work.  
https://www.amazon.com/gp/product/B00FB45USW/
I see "SUS_USB-AC56_8812AU" on the list of supported devices but I installed it and no luck. 
What does the AU stand for? Australia, I live in US would the model change?  Not sure where to find the full model number. 

I also tried with this one and no luck.
https://www.amazon.com/dp/B0159222VS/ 

I'm running Mojave 10.14.5 with the latest Clover boot loader.  I do see the RtWlanU and RtWlanU1827 in my kexts/other folder inside my EFI bootloader. 

I did see the network connections for half a second at one point and then it never worked again. I do no see the app asking for permission after the install. 

Any help would be appreciated

Thank you

**Comment by chris1111** [comment]
Sorry but your not the only one with an issue with the ASUS adapter and I really don't know why??? 
The PCI Expres card Rosewill RNX-AC1900PCE is not support

Maybe try a different release for your Asus adapter, let me know if one of them work

**Comment by daniel-farina** [comment]
Update:
I got it work with the drivers listed on the official page. I had installed the clover drivers and then installed the utility from here for MacOs: https://www.asus.com/us/Networking/USBAC56/HelpDesk_Download/

It looks like it overwrote the BarApp and maybe a few other things:
![image](https://user-images.githubusercontent.com/13665117/59931038-1c804000-9412-11e9-95a7-f1e9d1fc8f4e.png)

I also added the app to the app to the accessibility settings, not sure if that helped:
![image](https://user-images.githubusercontent.com/13665117/59931087-39b50e80-9412-11e9-8cd7-c2fcc78988a3.png)

**Comment by chris1111** [comment]
But you have a double Drivers, your ASUS Utility installed drivers in S/L/E and I am pretty sure its work with the lattes Drivers here from Clover Your Utility works for El Capitan
