### ISSUE TITLE
8723BE - PCI Support

### ISSUE THREAD

**Issue by albyvar** [chris1111/Wireless-USB-Adapter-Clover#2]
Hi, I have the Realtek 8723be PCI card, since it should be the same of 8723bu but one is usb, the other pci, and probably needs just some edits in the kext info.plist to replace IOUSBDevice with IOPCIDevice, could you please add support for it?

I tried doing this but I don't know what the 8723be productID and vendorID are (Figured are not the same of the PCI values)

**Comment by chris1111** [comment]
Sorry late replying 
Not supported for Mini PCI e card Realtek on macOS. 
Replace with compatible hardware.

**Comment by albyvar** [comment]
Ok, thanks anyway
