### ISSUE TITLE
Can't see the network list, but can connect network by add SSID and password

### ISSUE THREAD

**Issue by ourfor** [chris1111/Wireless-USB-Adapter-Clover#20]
- The version of current operation system is ` macOS catalina 10.15 beta `, the version of ` Wireless-USB-Adapter-Clover ` is ` Wireless USB Adapter Clover-V7 ` 

- I follow the steps on github readme ` Instructions `

> here is the screenshot 

![截屏2019-06-29上午9 40 14](https://user-images.githubusercontent.com/33711476/60378342-c9327100-9a53-11e9-84e6-dd4e9f3855c8.png)

![截屏2019-06-29上午9 40 28](https://user-images.githubusercontent.com/33711476/60378345-ce8fbb80-9a53-11e9-81cf-ed6f75360581.png)

![截屏2019-06-29上午9 45 22](https://user-images.githubusercontent.com/33711476/60378346-d3ed0600-9a53-11e9-8565-f6d94992f7f4.png)

**Comment by chris1111** [comment]
Thats really strange ! Looks like a bug in Catalina beta ??

**Comment by ourfor** [comment]
I don't know。😅

**Comment by daniel-farina** [comment]
Same here with Mojave: 

The list of networks does not show but manually entering the network name and password works. 

for the AC56 I used the network name and then WPA_2 for authentification type.


Thank you

**Comment by blackadmin** [comment]
On Mojave facing same issue, connecting fine but no scan results. :(
