### ISSUE TITLE
netgear A6100 getting signal but never connecting

### ISSUE THREAD

**Issue by hachirotahoshino** [chris1111/Wireless-USB-Adapter-Clover#26]
Hi,

I am on a AMD hackintosh,

adaptator is USB Netgear DA6100

installation ok

device seen

when i click the menu. see the networks

if i choose a network i have the password prompt window

then it never connects.

tried 3 different SSIDs

is there anything i can give you to help me? logs, whatever?

Thanks

**Comment by chris1111** [comment]
Which kernel? What AMD ? its difficult  to resolve issue on AMD I dont have  AMD for test.
Try différant USB Port ?
Check on AMD Forum
