### ISSUE TITLE
Cannot connect to wpa2 enterprise

### ISSUE THREAD

**Issue by MmDawN** [chris1111/Wireless-USB-Adapter-Clover#28]
NIC : RTL8812AU
Driver : Clover-V7
System Version : macOS Mojave 10.14.6 
Issues : I cannot connect to the WPA2-Enterprise wireless network such as the eduroam and public network in my campus using the usb wireless card.

**Comment by luisdecker** [comment]
There was some solution for this issue? I'm having the same problems with EDUROAM (Can't get ip)
