### ISSUE TITLE
V7 - nano t2u

### ISSUE THREAD

**Issue by madhav0922** [chris1111/Wireless-USB-Adapter-Clover#32]
Whenever i plugin my tp-link t2u nano adapter, the system just runs into a kernel panic and reboots straight away.
i am able to reach the password pane though. As soon as i enter my password and hit enter, it reboots

**Comment by chris1111** [comment]
On what macOS? I never heard a problem like this
SIP is désactivate ?

**Comment by madhav0922** [comment]
I am using a hackintosh.
Mac os Mojave 10.14
On v6 i had the tp link TL-WN725N which works great on both v6 and v7 unline t2u nano

**Comment by chris1111** [comment]
> I am using a hackintosh.
> Mac os Mojave 10.14.3
> On v6 i had the tp link TL-WN725N which works great on both v6 and v7 unlike t2u nano

Why not Updating macOS to to 10.14.6 ?

**Comment by madhav0922** [comment]
Because for some reason it gets stuck while updating. I'll have to redo mac from scratch to update..so when i'll get time i'll update.
Will updating fix the issue though? So i'll report after updating.
One more thing that with the default driver provided by tp-link on their official site, t2u nano is working.
