### ISSUE TITLE
wifi recognize as ethernet

### ISSUE THREAD

**Issue by tom8zds** [chris1111/Wireless-USB-Adapter-Clover#36]
I'm using tplink 823n v2. 
1. can't search for signal list. But it can connect to manual added target
2. every boot will refresh setting (proxy etc) and the name of the connection is Ethernet
3. system treat is as illegal internal Ethernet device so It can't login to icloud

I guess the problem is that system recognize it as Ethernet device instead of Wi-Fi adapter, so user can only set up connection manually. And the driver load up the device after utility start, the Ethernet fake provide by clover does not effect the driver.

any possibility to fix that

**Comment by chris1111** [comment]
Your wrong it does not change anything it is recognized ethernet or Wifi
 see the video from  **Wireless USB Adapter** Its the same Drivers and App
[![Modular Image Creation](https://i.ibb.co/K5bFrB5/VIDEO.png)](https://youtu.be/x_mg0lCSghM)
