### ISSUE TITLE
Can`t acces wifi requres a WPA2 Enterprise AES password

### ISSUE THREAD

**Issue by firefhy** [chris1111/Wireless-USB-Adapter-Clover#37]
The icon is connected, but the network can`t be used

**Comment by songyaru** [comment]
the same isuure. only connet no password wifi

**Comment by jinm1988** [comment]
the same issue. always connecting.

**Comment by Zheng-Jiakun** [comment]
Same issue. always connecting... I just want to connect to the eduroam in my school.

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Adapter/issues/1
