### ISSUE TITLE
Support for Archer T2U v2

### ISSUE THREAD

**Issue by wilsonnkwan** [chris1111/Wireless-USB-Adapter-Clover#38]
Hi, I notice that you have support for Archer T2U nano, T3U and T4U, is it possible to add support for Archer T2U v2? Help please? thanks.

**Comment by chris1111** [comment]
T2UH not using the same driver, its Mediatek RT2870USBWirelessDriver.kext

Follow this I have the same Adapter
https://github.com/chris1111/WIFI-Dlink-Catalina-Panel-V2

**Comment by wilsonnkwan** [comment]
Oh, so I have to install your other project and this theoretically will work? :D
