### ISSUE TITLE
64 bit app

### ISSUE THREAD

**Issue by llyonard** [chris1111/Wireless-USB-Adapter-Clover#4]
Hi, im using an amd hack and i need to build the statusbarapp in 64 bit, without it'll not work on mojave. Do you have the source?

**Comment by chris1111** [comment]
> Hi, im using an amd hack and i need to build the statusbarapp in 64 bit, without it'll not work on mojave. Do you have the source?

its work on Mojave I have install since long time

**Comment by llyonard** [comment]
Yep but on amd the current kernels only support 64-bit binaries.

**Comment by chris1111** [comment]
ok Undestand
Source of the app is not available anywhere

**Comment by llyonard** [comment]
Ok thanks anyway.
