### ISSUE TITLE
RTL 8187 Not working with Wireless Utility.

### ISSUE THREAD

**Issue by Vikesyy** [chris1111/Wireless-USB-Adapter-Clover#41]
Hello,

macOS Mojave recognized my wifi, but your Utility doesn't show my device nor the setting. Please I request you to add functionality for my device RTL 8187. I will be grateful.

![Screenshot 2019-11-07 at 4 39 31 PM](https://user-images.githubusercontent.com/38877518/68472726-f2091500-0242-11ea-982c-c9a07625b0a0.png)

Thank You

**Comment by chris1111** [comment]
of course not working your adapter not using the same drivers and its not support by the utility
You are using rtl8187.kext
![Capture d’écran, le 2019-11-08 à 06 25 36](https://user-images.githubusercontent.com/6248794/68473392-e0971d00-01f0-11ea-9646-805146b884e1.png)

**Comment by Vikesyy** [comment]
I didn’t use any Kext, it recognised it. And how my device is RTL 8187, why isn’t it working?

**Comment by chris1111** [comment]
it is recognized if you install the package that corresponds to your usb adapter.
