### ISSUE TITLE
TL-WN725N 3.0 免驱版显示 No USB-WiFi Plug in

### ISSUE THREAD

**Issue by lable** [chris1111/Wireless-USB-Adapter-Clover#42]
TL-WN725N 3.0 免驱版显示 No USB-WiFi Plug in

**Comment by chris1111** [comment]
Change USB port then reboot
Also veriying config.plist
,### View ➣ [➤ You must have set injectkexts to Yes in the Clover config.plist](https://i25.servimg.com/u/f25/18/50/18/69/captu819.png)

**Comment by lable** [comment]
config.plist -> 


	<dict>
		<key>CustomUUID</key>
		<string>FB78CF39-348B-441A-91A9-44157C41B953</string>
		<key>InjectKexts</key>
		<string>Yes</string>
		<key>InjectSystemID</key>
		<true/>
	</dict>

**Comment by nxnyk** [comment]
> config.plist ->
> 
> ```
> <dict>
> 	<key>CustomUUID</key>
> 	<string>FB78CF39-348B-441A-91A9-44157C41B953</string>
> 	<key>InjectKexts</key>
> 	<string>Yes</string>
> 	<key>InjectSystemID</key>
> 	<true/>
> </dict>
> ```

老哥你解决了吗？
