### ISSUE TITLE
Plans to support rt8811cu?

### ISSUE THREAD

**Issue by jarmster** [chris1111/Wireless-USB-Adapter-Clover#43]
Just got my new dual band wireless adaptor for my hackintosh in the mail today. Guess what? doesn't work.lol
Its a RT8811cu. Do you plan on adding support for this adaptor?

**Comment by chris1111** [comment]
I am guessing its Asus USB adapter ?
I don't think its old but RT8811cu not impossible from Realtek and the next update for Catalina who will be soon. 
This will be to see!
