### ISSUE TITLE
Request support with RTL8811CU

### ISSUE THREAD

**Issue by shm007g** [chris1111/Wireless-USB-Adapter-Clover#46]
RTL8811CU is similar with RTL8811AU as I see. But RTL8811CU not in the support list. Could you please check and support RTL8811CU as well?

Much appreciated !

**Comment by chris1111** [comment]
> RTL8811CU is similar with RTL8811AU as I see. But RTL8811CU not in the support list. Could you please check and support RTL8811CU as well?
> 
> Much appreciated !

This Driver is made foe Windows
See official Realteak drivers
[For Realtek USB WLAN Family Controller.](https://www.realtek.com/en/component/zoo/category/rtl8811cu-software)

**Comment by shm007g** [comment]
I mean I could use this RTL8811CU(CF-811AC) on macOS 10.14 with official driver which may fail for its 32-bit-build. Could you make this RTL8811CU work on Catalina?

![image](https://user-images.githubusercontent.com/16999665/69952186-9c6a1480-1531-11ea-9855-4ff7b5e2d33b.png)

**Comment by chris1111** [comment]
please upload driver package here

**Comment by shm007g** [comment]
[RTLWlanU_MacOS10.9_MacOS10.14_Driver_1830.20.b31_1827.4.b32_UI_5.0.8.b4.zip](https://github.com/chris1111/Wireless-USB-Adapter-Clover/files/3910782/RTLWlanU_MacOS10.9_MacOS10.14_Driver_1830.20.b31_1827.4.b32_UI_5.0.8.b4.zip)

Really Appreciated !

**Comment by chris1111** [comment]
[Did you try latest release  ](https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/V11)

**Comment by shm007g** [comment]
@chris1111  I tried last weekend, it works fine. Really thx.
