### ISSUE TITLE
TL-WN823N not recognized

### ISSUE THREAD

**Issue by NotDaba** [chris1111/Wireless-USB-Adapter-Clover#48]
Hello.
First of all, thanks for the work you are doing.
My USB WIFI can't be recognised.
Maybe it's because it's V3 but not sure about this. 
![Schermata 2019-12-17 alle 08 44 05](https://user-images.githubusercontent.com/58988586/71016696-650b7400-20aa-11ea-86b0-3bafc49ca484.png)

**Comment by chris1111** [comment]
Follow the guide correctly maybe a reboot is neneccesary but the WN823N V3 work and is already test by lots of people

**Comment by NotDaba** [comment]
I'm really sure about having followed all the steps at 100%.
Tried all my USB port on notebook, tried also lot of restart.
![Schermata 2019-12-18 alle 05 08 04](https://user-images.githubusercontent.com/58988586/71088873-642f1c80-2154-11ea-8319-c3f557f7401c.png)

**Comment by Mr-Bubble** [comment]
Hot boot from windows to Max, it works，You try

**Comment by NotDaba** [comment]
This worked. 
Thanks a lot. 
--
Inviato da Libero Mail per Android domenica, 22 dicembre 2019, 08:15AM +01:00 da Bubble  notifications@github.com :

**Comment by Mr-Bubble** [comment]
You're welcome, cold boot doesn't work, this is obviously a bug, hope the author can fix it

**Comment by NotDaba** [comment]
Yea! Thanks a lot for real! 
--
Inviato da Libero Mail per Android domenica, 22 dicembre 2019, 08:32AM +01:00 da Bubble  notifications@github.com :

**Comment by Mr-Bubble** [comment]
@chris1111
