### ISSUE TITLE
source release

### ISSUE THREAD

**Issue by coderobe** [chris1111/Wireless-USB-Adapter-Clover#49]
Hey, this app is super useful and works great, though i would love to see the source code for it as i have some bug fixes for the app.
Can you push the code to this repository?

**Comment by chris1111** [comment]
I am not the developer; I do not have the source code otherwise I will have already put it.
this project to start from old drivers and the goal is to get the majority of USB adapters in the latest macOS.

**Comment by coderobe** [comment]
I see, thanks for the info

**Comment by Mr-Bubble** [comment]
Can you share your repaired version
