### ISSUE TITLE
Can you please add support for TP-Link WN821N V4?

### ISSUE THREAD

**Issue by Lolihunter1337** [chris1111/Wireless-USB-Adapter-Clover#5]

**Comment by chris1111** [comment]
> No description provided.

Used latest release and change Drivers on Clover
let me known if that working
[Archiver.zip](https://github.com/chris1111/Wireless-USB-Adapter-Clover/files/2707890/Archiver.zip)

**Comment by Lolihunter1337** [comment]
is it possible to try on a VM ware first? so using the "real mac" version?

**Comment by chris1111** [comment]
> is it possible to try on a VM ware first? so using the "real mac" version?

try
 I don't know, I am not use VM

**Comment by Lolihunter1337** [comment]
doesnt work. it gets detected but doesnt show any Network i also tried https://github.com/chris1111/Wireless-USB-Adapter/releases/tag/V2 but same problem

**Comment by chris1111** [comment]
> doesnt work. it gets detected but doesnt show any Network i also tried https://github.com/chris1111/Wireless-USB-Adapter/releases/tag/V2 but same problem

Thanks to report I think support WN821N V4 is drop after Yosemite 10.10

**Comment by Lolihunter1337** [comment]
Got it working on Sierra 10.12 thanks man
