### ISSUE TITLE
Archer T4U V3 Airplay not working

### ISSUE THREAD

**Issue by TheWorse** [chris1111/Wireless-USB-Adapter-Clover#50]
Hey! Recently I bought this adapter for a hackintosh (laptop Asus hero II) and wifi works perfectly, but once I try to airplay the audio to my HomePod it doesn't work at all, even more the wifi stops working correctly and pages do not load, if I try to reset the wifi it keeps loading and loading indefinitely and i need to restart the laptop. What exactly is the issue here? Also airplay works fine through ethernet with the Realtek kext. thanks in advance

**Comment by chris1111** [comment]
I don't believe AirPlay works with a WIFI USB adapter
