### ISSUE TITLE
During booting and shutdown,  prints "<=== HalUsbInMpdu()" often.

### ISSUE THREAD

**Issue by dnhkng** [chris1111/Wireless-USB-Adapter-Clover#51]
Hi,

After installing a T2U Nano dongle, I see the message:
`<=== HalUsbInMpdu()`

printing about 10 times a second during bootup and shutdown. Is this normal behavior?

**Comment by chris1111** [comment]
Yes this message is normal in verbose mode -V

**Comment by lazd** [comment]
This actually prints non-stop, even after boot, several times per second. This message should be disabled.

**Comment by chris1111** [comment]
The release V11 its a first official beta driver for Catalina so If your not happy with the release V11 use release V10 this message not exist
https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/V10

**Comment by chris1111** [comment]
Issue is resolved with the [Release V13](https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/v13)
