### ISSUE TITLE
TL-WN823N not recognized 

### ISSUE THREAD

**Issue by Mr-Bubble** [chris1111/Wireless-USB-Adapter-Clover#53]
cold boot doesn't work, but Hot boot from windows to Mac, it works，plese fix it

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Adapter-Clover/issues/48

**Comment by Mr-Bubble** [comment]
@chris1111 cold boot doesn't work, this is obviously a bug, hope the author can fix it

**Comment by chris1111** [comment]
> @chris1111 cold boot doesn't work, this is obviously a bug, hope the author can fix it

what do you mean by cold boot ?

**Comment by Mr-Bubble** [comment]
Boot from shutdown status to Mac it no work，boot from windows to Mac, it works

**Comment by chris1111** [comment]
never heard of that, **I have 5 adapters** and it all works whether I reboot or do a Shotdown and I also have a dual boot windows 10

**Comment by Mr-Bubble** [comment]
Not only I have this problem, #48 also have this issue

**Comment by chris1111** [comment]
> Not only I have this problem, #48 also have this issue

I have the TL-WN823N I will show you some things today

**Comment by chris1111** [comment]
## Video ⬇︎
[![Modular Image Creation](https://i.ibb.co/K5bFrB5/VIDEO.png)](https://youtu.be/ijKOL-VU93s)

So this the prouve of working check issue on your System
