### ISSUE TITLE
Not working on after updating to 10.15.2

### ISSUE THREAD

**Issue by iVarunPatel** [chris1111/Wireless-USB-Adapter-Clover#54]
Recently i have updated my hackintosh to 10.15.1 to 10.15.2. After updating i am getting message "No USB-Wifi plug in". **InjectKext** is also set to **Yes**. 

Please help.

**Comment by chris1111** [comment]
What is the adapter ?
Regarding the utility, there is no reason why it does not work. Look on your side and test usb port or system permission but there is nothing I can do because it works.

**Comment by Mr-Bubble** [comment]
Hot boot from windows to Mac, it works，You try

**Comment by iVarunPatel** [comment]
@Mr-Bubble How can i do this? I'm using only mac.

**Comment by chris1111** [comment]
> Hot boot from windows to Mac, it works，You try

Of topic !
 stop to post everywhere because I will consider spamming
