### ISSUE TITLE
The download speed could not be detected

### ISSUE THREAD

**Issue by D257-zhongjian** [chris1111/Wireless-USB-Adapter-Clover#57]
Installed software can not monitor download speed, web speed can be measured

**Comment by dobpilot** [comment]
This is a driver, driver is a soft for communicate os and hardware. Monitoring task is not primary for the driver, use third party services and tools like www.speedtest.net or inet.ya.ru or my favorite iperf

**Comment by aanfarhan** [comment]
Actually I have the same problem, I am using System Toolkit to monitor network traffic. On Mojave the download speed is detected using the original driver, but when I used this driver on Catalina the download speed is not detected. Maybe it's really from the driver?
