### ISSUE TITLE
hot plug problem

### ISSUE THREAD

**Issue by shm007g** [chris1111/Wireless-USB-Adapter-Clover#59]
1. If I remove the usb wifi for about 10 seconds, and put it back, wifi will reconnect.
2. If I remove the usb wifi for about 2 minutes, and put it back, wifi will **NOT** reconnect.

I may share the usb wifi for anther device, this make me really sad! For It can't  reconnect after several minutes.

System: catalina 10.15.2
Board: Asus Prime B360M-A
Wifi: comfast CF-811AC(RTL8811CU)

This really matters to me.

Thx! Best Wishes!

**Comment by chris1111** [comment]
It depends I think on the brand of adapter because I have five USB Wifi adapters and only one has difficulty reconnecting, it's the Edimax EX7722Utn v2
