### ISSUE TITLE
OpenCore Bootloader

### ISSUE THREAD

**Issue by NotDaba** [chris1111/Wireless-USB-Adapter-Clover#62]
Can we have an installer for OpenCore?

**Comment by chris1111** [comment]
no

**Comment by dorald** [comment]
I just managed to install (manually) on OpenCore. Just extract the two Kexts from this clover installer and copy to /EFI/OC/Kexts then edit config.plist to add the two kexts under Kernel -> Add
Worked for me :)

**Comment by vimcaw** [comment]
> I just managed to install (manually) on OpenCore. Just extract the two Kexts from this clover installer and copy to /EFI/OC/Kexts then edit config.plist to add the two kexts under Kernel -> Add
> Worked for me :)

@Dorald Thank you for sharing, but I only get some strange files, how do you extract the kexts?

The content of clover installer: 

![image](https://user-images.githubusercontent.com/21964227/77253362-92ad1e00-6c94-11ea-8b30-fa3d509739b9.png)

The content of each *.pkg file: 

![image](https://user-images.githubusercontent.com/21964227/77253367-9e98e000-6c94-11ea-8596-64f525772555.png)

The Resources folder only has some text files.

**Comment by chris1111** [comment]
see video here
https://github.com/chris1111/macOS-Extractor

**Comment by vimcaw** [comment]
@chris1111 Got it 😀, Thanks!

**Comment by tanpengsccd** [comment]
after install pkg, U find ESP /EFI/CLOVER/kexts/Other RtWlanU1827.kext, RtWlanU.kext , and manual config OC config.plist
