### ISSUE TITLE
EDIMAX EW-7811Un Not detected.

### ISSUE THREAD

**Issue by nojohnso** [chris1111/Wireless-USB-Adapter-Clover#65]
Two installation attempts, each after a fresh install and I'm still not able to use my Edimax nano. Clover settings match those specified during installation.

**Comment by chris1111** [comment]
Try release V10 please

**Comment by nojohnso** [comment]
Unfortunately the result is the same. Plugged it into a Windows machine and it still works so it's not dead... any other ideas? Thanks for your help.

**Comment by chris1111** [comment]
Try to change USB port

**Comment by IceCreamCone** [comment]
I had the same issue with the EW-7811Un. I solved it by downgrading to v9.

**Comment by chris1111** [comment]
> I had the same issue with the EW-7811Un. I solved it by downgrading to v9.

Thanks 👍🏻
