### ISSUE TITLE
TL-WN725N 3.0 No USB-WiFi Plug in

### ISSUE THREAD

**Issue by nxnyk** [chris1111/Wireless-USB-Adapter-Clover#67]

**Comment by nxnyk** [comment]
![image](https://user-images.githubusercontent.com/42330422/72217292-527c4180-3567-11ea-8060-cf35c3cc8e6e.png)
because 8188GU not support？

**Comment by chris1111** [comment]
See https://github.com/chris1111/Wireless-USB-Adapter-Clover/issues/34
