### ISSUE TITLE
Problem with adapter 

### ISSUE THREAD

**Issue by Milesy** [chris1111/Wireless-USB-Adapter-Clover#68]
I have a Ralink 5370 adapter but it’s not being detected. I thought it was supported?

**Comment by chris1111** [comment]
Ralink 5370 its here 
https://github.com/chris1111/WIFI-Dlink-Catalina-Panel-V2

**Comment by Milesy** [comment]
Thanks. I don’t have Catalina unfortunately. I’m still on high Sierra as I need specific FireWire support

**Comment by chris1111** [comment]
> Thanks. I don’t have Catalina unfortunately. I’m still on high Sierra as I need specific FireWire support
Use this programme
https://github.com/chris1111/USB-Wireless-Utility

**Comment by chris1111** [comment]
> Thanks. I don’t have Catalina unfortunately. I’m still on high Sierra as I need specific FireWire support

Use this programme
https://github.com/chris1111/USB-Wireless-Utility

**Comment by Milesy** [comment]
That works. Brilliant. Thanks
