### ISSUE TITLE
Issues while requires username and passwd

### ISSUE THREAD

**Issue by billhhh** [chris1111/Wireless-USB-Adapter-Clover#69]
My uni has public wifi which requires username and passwd, however the adapter does not working...

**Comment by chris1111** [comment]
Elaborate please I don't understand your issue

**Comment by billhhh** [comment]
Hi Chris,

Thank you for your rapidly reply. Sorry for not elaborating the question clearly.

The adapter works in most of my situations. But the public wifi hotspot of my uni requires username and passwd, using a different Encryption type --- EAP. After I typed in the username and passwd, it disappeared.
BTW, I am using a relatively old version, May I know the lastest version has fixed it or there is a way to access the EAP encrypted network?

Thank you so much!

**Comment by chris1111** [comment]
See here
https://github.com/chris1111/Wireless-USB-Adapter-Clover/issues/37

**Comment by billhhh** [comment]
Thank you, Chris
