### ISSUE TITLE
works fine-but only if booted with dongle

### ISSUE THREAD

**Issue by Pedroooow** [chris1111/Wireless-USB-Adapter-Clover#71]
Hey ! 
Merci Chris pour ce programme bien pratique ;) 

Just 1 question: it works fine with my wifi dongle but only if I boot with the dongle plugged in. 

If I boot connected with ethernet at my desktop and decide to unplug my laptop to go work elsewhere, I have to reboot the computer after having plugged the dongle. 

Is there any way to refresh the software / kill it and relaunch without having to reboot ? 

Thanks !

**Comment by chris1111** [comment]
Thanks
I don't know any way to get there, if you find come tell us .
Thank you for bringing it.

**Comment by hacker1024** [comment]
This is odd, it seems to work fine when the kexts are installed the normal way (not through Clover).
Can we leave this issue open? It hasn't been resolved yet.

**Comment by chris1111** [comment]
> This is odd, it seems to work fine when the kexts are installed the normal way (not through Clover).
> Can we leave this issue open? It hasn't been resolved yet.
yes it is true that it works with this one [Wireless USB Adapter](https://github.com/chris1111/Wireless-USB-Adapter)  but what does it change whether this issue is closed or open

**Comment by chris1111** [comment]
Fix
https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/V15
