### ISSUE TITLE
Can you make it support 360 wifi(RT2780)?

### ISSUE THREAD

**Issue by jay763190097** [chris1111/Wireless-USB-Adapter-Clover#77]

**Comment by chris1111** [comment]
RT2780
https://github.com/chris1111/Wireless-Ralink-Panel-Utility

**Comment by jay763190097** [comment]
@chris1111 But it has some problems.
RT2870USBWirelessDriver.kext can not be loaded.
The taskbar also can not see [no connection].
I fund on the system preferences setting page, then I opened it, but  it show me can not find device.
