### ISSUE TITLE
MT7662

### ISSUE THREAD

**Issue by arthurmelo88** [chris1111/Wireless-USB-Adapter-Clover#8]
Hi @chris1111 
Thx for this awesome work!
My adapter is MT7662
I really loved this driver user interface, but my usb adapter isnt compatible, only compatible with your other driver version https://github.com/chris1111/WIFI-Network-macOS-High-Sierra
There is a way to port it to this driver using clover activation?
Every reboot I must run Wifi application to start scanning wifi connection XD

**Comment by chris1111** [comment]
> Hi @chris1111
> Thx for this awesome work!
> My adapter is MT7662
> I really loved this driver user interface, but my usb adapter isnt compatible, only compatible with your other driver version https://github.com/chris1111/WIFI-Network-macOS-High-Sierra
> There is a way to port it to this driver using clover activation?
> Every reboot I must run Wifi application to start scanning wifi connection XD

Thanks @arthurmelo88 
there is no way; you have to use the other
in clover it does not work well.
