### ISSUE TITLE
RTL8188ETV Support

### ISSUE THREAD

**Issue by nikibeatz** [chris1111/Wireless-USB-Adapter-Clover#81]
I installed the latest version on Wireless USB Adapter Clover on macOS Mojave, but when I connect the adapted RTL8188ETV it's showing No USB-WIFI Plug in and it's not working. On windows 10 it's working fine and this is the full device description which windows give: Realtek RTL8188ETV Wireless LAN 802.11n USB 2.0 Network Adapter.

I also tried switching USB ports, rebooting, nothing helped.
Clover InjectKext is set to Yes.

**Comment by chris1111** [comment]
Its not support on macOS
