### ISSUE TITLE
No USB-WIFI Plug in 

### ISSUE THREAD

**Issue by Nishit-Chauhan** [chris1111/Wireless-USB-Adapter-Clover#82]
i m using catalina 10.15.3, and i have installed latest V15 installed, but not able to use my USB wifi adapter, 
also i have verified the Inject kext = yes in info.plist and after Driver installed also verified that both kext are placed in CLOVER/kext/other/ let me attach screenshot for you. 
i have notice that in system preference no wifi adapter detected in Networks, 
please help me to fix this, Thanks 

![Screenshot 2020-07-11 at 10 31 52 AM](https://user-images.githubusercontent.com/45855322/87217030-b2ab3f00-c362-11ea-9649-cb7d71ba6ca1.png)
![Screenshot 2020-07-11 at 10 38 04 AM](https://user-images.githubusercontent.com/45855322/87217035-be970100-c362-11ea-8fd1-8c740fad8415.png)
![Screenshot 2020-07-11 at 10 38 21 AM](https://user-images.githubusercontent.com/45855322/87217038-c5257880-c362-11ea-8a96-62e45a8178ef.png)
![Screenshot 2020-07-11 at 10 37 03 AM](https://user-images.githubusercontent.com/45855322/87217039-c787d280-c362-11ea-9990-b77da03c3569.png)

**Comment by chris1111** [comment]
What is your adapter brand?

**Comment by Nishit-Chauhan** [comment]
https://www.amazon.in/CityShoppy-900Mbps-Wireless-Adapter-Generation/dp/B07FK33GZG

**Comment by chris1111** [comment]
Do you have the MacOS drivers?

**Comment by chromer030** [comment]
@Nishit-Chauhan , This adapter is based on RTL8188 and on Linux can be loaded via rtl8188fu module , i don't know whether Realtek implemented support for this chip on macOS kexts or not , because this chip is somehow old.

**Comment by basser2** [comment]
my problem is that I have to plugin the USB WiFi before my hackintosh boot,otherwise I can't use it. why and how to fix it?

**Comment by basser2** [comment]
> i m using catalina 10.15.3, and i have installed latest V15 installed, but not able to use my USB wifi adapter,
> also i have verified the Inject kext = yes in info.plist and after Driver installed also verified that both kext are placed in CLOVER/kext/other/ let me attach screenshot for you.
> i have notice that in system preference no wifi adapter detected in Networks,
> please help me to fix this, Thanks
> 
> ![Screenshot 2020-07-11 at 10 31 52 AM](https://user-images.githubusercontent.com/45855322/87217030-b2ab3f00-c362-11ea-9649-cb7d71ba6ca1.png)
> ![Screenshot 2020-07-11 at 10 38 04 AM](https://user-images.githubusercontent.com/45855322/87217035-be970100-c362-11ea-8fd1-8c740fad8415.png)
> ![Screenshot 2020-07-11 at 10 38 21 AM](https://user-images.githubusercontent.com/45855322/87217038-c5257880-c362-11ea-8a96-62e45a8178ef.png)
> ![Screenshot 2020-07-11 at 10 37 03 AM](https://user-images.githubusercontent.com/45855322/87217039-c787d280-c362-11ea-9990-b77da03c3569.png)

try to plugin the USB WiFi before your system boot?

**Comment by Nishit-Chauhan** [comment]
thanks for the response @chris1111 , @chromer030  and @basser2. but actually i have returned this wifi chip, so i m closing this issue
