### ISSUE TITLE
Is it possible to add support for RTL8188EUS?

### ISSUE THREAD

**Issue by VicoErv** [chris1111/Wireless-USB-Adapter-Clover#85]
I already turn on injectKext, and tried both clover and non clover edition of this app. And I have the CD driver. But I can't install it on catalina.

Thank you

**Comment by VicoErv** [comment]
[rtl8188eu8.pkg.zip](https://github.com/chris1111/Wireless-USB-Adapter-Clover/files/4941273/rtl8188eu8.pkg.zip)
[rtl8192cu8.pkg.zip](https://github.com/chris1111/Wireless-USB-Adapter-Clover/files/4941274/rtl8192cu8.pkg.zip)
[rtl8192su8.pkg.zip](https://github.com/chris1111/Wireless-USB-Adapter-Clover/files/4941275/rtl8192su8.pkg.zip)

**Comment by chris1111** [comment]
RTL8192SU8.kext not support
