### ISSUE TITLE
Diff from official drivers?

### ISSUE THREAD

**Issue by francisceril** [chris1111/Wireless-USB-Adapter-Clover#87]
Not really an issue but what would be the advantage or difference of this driver from the official TP-Link driver? I have the Archer T3U if it matters.
Delete if not appropriate here.

Thanks.

**Comment by chris1111** [comment]
It would surprise me that the official TpLink one is more recent than this one

**Comment by francisceril** [comment]
Indeed their driver is still in beta. Anyway, can you provide just the kexts? I'm using OpenCore for my bootloader. The installer I believe is for Clover setup.
Thank you.

**Comment by chris1111** [comment]
> Indeed their driver is still in beta. Anyway, can you provide just the kexts? I'm using OpenCore for my bootloader. The installer I believe is for Clover setup.
> Thank you.

https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter
