### ISSUE TITLE
Kernel panic on mojave 10.14.3

### ISSUE THREAD

**Issue by maz-1** [chris1111/Wireless-USB-Adapter-Clover#9]
My WLAN device is COMFAST CF-916AC (RTL8811AU)
As soon as I try to connect to a 2.4ghz hotspot the system panics
Panic log: https://gist.github.com/maz-1/b155930f15948089519902dcf2d3d443

**Comment by chris1111** [comment]
> My WLAN device is COMFAST CF-916AC (RTL8811AU)
> As soon as I try to connect to a 2.4ghz hotspot the system panics
> Panic log: https://gist.github.com/maz-1/b155930f15948089519902dcf2d3d443

latest Release of Mojave update is 10.14.3 (18D109) no issue here

**Comment by chris1111** [comment]
OK try Release V5 but first of all, uninstall the V4
https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/V5

**Comment by maz-1** [comment]
> OK try Release V5 but first of all, uninstall the V4
> https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/V5

Great, it works.
