### ISSUE TITLE
crash on catalina

### ISSUE THREAD

**Issue by petkoivanov** [chris1111/Wireless-USB-Adapter-Clover#91]
i reinstalled catalina twice. 
first time i was connecting OK to 5g. I messed up some kext (noob) so had to reinstall.
Now i can connect OK to my 2.4ghz wireless but if i try to connect to 5hz my pc restarts. 
I tried to look for logs but I cant find anything useful.

Catalina Version : 10.15 (19A583) (fresh install)

wifi usb adapter is this:
https://www.brostrend.com/Product.aspx?ProductId=325
(their driver does not load on catalina).

Let me know what else i can provide, 
Thanks in advance

P.S. i uninstalled and installed about 3 times, same result. I made sure SIP is disabled.

**Comment by chris1111** [comment]
See this
https://github.com/chris1111/Wireless-USB-Adapter/issues/66#issuecomment-657076077
