### ISSUE TITLE
[ehancement] Identify wireless USB device type as WiFi rather than ethernet

### ISSUE THREAD

**Issue by g1augusto** [chris1111/Wireless-USB-Adapter-Clover#92]
Hi Chris,

Is it possible to make the USB Wireless device to be recognized as a device type Wifi rather than ethernet?

Thanks

**Comment by chris1111** [comment]
> Hi Chris,
> 
> Is it possible to make the USB Wireless device to be recognized as a device type Wifi rather than ethernet?
> 
> Thanks

Yes on old macOS version

**Comment by g1augusto** [comment]
Thank you,

Can you let me know which version of macos and how ?

I just need it for some tests and it would help me a lot

**Comment by chris1111** [comment]
Capitan and all other lower macOS  I think

**Comment by g1augusto** [comment]
Thanks anyway,

I tried and is the same, it works with TPlink drivers but recognizes it always like an ethernet card
