### ISSUE TITLE
Installation prbl

### ISSUE THREAD

**Issue by Jude-A** [chris1111/Wireless-USB-Adapter-Clover#93]
Hey, I have a little problem, when I download the zip or tar fil and decompressed them, I just fin the wifi color installer and not the real driver. What's the solution ?

**Comment by chris1111** [comment]
Download the release 
https://github.com/chris1111/Wireless-USB-Adapter-Clover#download-latest-release--wireless-usb-adapter-clover-v16pkg-

**Comment by Jude-A** [comment]
it does not work

**Comment by Jude-A** [comment]
![Capture d’écran 2020-10-22 à 07 00 28](https://user-images.githubusercontent.com/60285285/96883036-c754a400-1434-11eb-8db7-a3c8c727f026.png)

**Comment by chris1111** [comment]
This is a Joke or what You have 9 link for Release
https://github.com/chris1111/Wireless-USB-Adapter-Clover#download-latest-release--wireless-usb-adapter-clover-v16pkg-
If you select the first link its the release V16

![Capture d’écran, le 2020-10-22 à 10 06 41](https://user-images.githubusercontent.com/6248794/96883444-6cc84180-144e-11eb-8e58-590ee663ba11.png)
