### ISSUE TITLE
driver installs in 10.13.4 but no wifi icon

### ISSUE THREAD

**Issue by jpmorrison** [chris1111/Wireless-USB-Adapter-Clover#98]
I installed v16 in High Sierra 10.13.4, rebooted. It shows up in System Preferences/Network but there's no status icon so can't connect to a wifi network.

I tried installing USB Wireless Utility and rebooted. Wireless Icon does not show networks,  Show Wireless Utility doesn't do anything

**Comment by chris1111** [comment]
why trying two different software and Driver ?
No description about the USB adapter
